language: rust
sudo: required
env:
    global:
        - LIBRARY_PATH=/usr/local/lib
        - LD_LIBRARY_PATH=/usr/local/lib
        - LD_RUN_PATH=/usr/local/lib
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true
script:
    - ./travis.sh
