language: rust
sudo: required
addons:
    apt:
        packages:
            - python3
            - python3-dev
env:
    global:
        - LIBRARY_PATH=/usr/local/lib
        - LD_LIBRARY_PATH=/usr/local/lib
        - LD_RUN_PATH=/usr/local/lib
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true
before_script:
    - wget https://bootstrap.pypa.io/get-pip.py
    - sudo python3 get-pip.py
    - rm get-pip.py
script:
    - ./travis.sh
