language: rust
addons:
    apt:
        packages:
            - libssl-dev
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true
script:
    - ./travis.sh
