[package]
name = "webthing"
version = "0.1.0"
authors = ["Mozilla IoT <iot@mozilla.com>"]
repository = "https://github.com/mozilla-iot/webthing-rust"
homepage = "https://github.com/mozilla-iot/webthing-rust"
license = "MPL-2.0"
readme = "README.md"
description = "Implementation of an HTTP Web Thing."

[dependencies]
actix = "0.5"
actix-web = { version = "0.5", features=["alpn"] }
bytes = "0.4"
chrono = "0.4"
futures = "0.1"
mdns = { git = "https://github.com/plietar/rust-mdns" }
openssl = "0.10"
serde_json = "1.0"
uuid = { version = "0.6", features = ["v4"] }
valico = "2.1"
