[package]
name = "webthing"
version = "0.13.0"
authors = ["Mozilla IoT <iot@mozilla.com>"]
repository = "https://github.com/mozilla-iot/webthing-rust"
homepage = "https://github.com/mozilla-iot/webthing-rust"
license = "MPL-2.0"
readme = "README.md"
description = "Implementation of an HTTP Web Thing."
edition = "2018"

[dependencies]
actix = "0.10"
actix-net = "0.2"
actix-service = "1.0"
actix-web = "3.0"
actix-web-actors = "3.0"
chrono = "0.4"
futures = "0.3"
get_if_addrs = "0.5"
hostname = "0.3"
libmdns = "0.4"
openssl = { version = "0.10", optional = true }
serde_json = "1.0"
uuid = { version = "0.8", features = ["v4"] }
valico = "3.4"

[dev-dependencies]
actix-rt = "1.1"
env_logger = "0.7"
rand = "0.7"

[features]
default = []
ssl = ["actix-web/openssl", "openssl"]
