[package]
name = "webthing"
version = "0.1.0"
authors = ["Mozilla IoT <iot@mozilla.com>"]
repository = "https://github.com/mozilla-iot/webthing-rust"
homepage = "https://github.com/mozilla-iot/webthing-rust"
license = "MPL-2.0"
readme = "README.md"
description = "Implementation of an HTTP Web Thing."

[dependencies]
actix-web = "0.5"
chrono = "0.4"
mdns = "0.2"
serde_json = "1.0"
valico = "2.1"
