name: Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-version: [
          'stable',
          'beta',
          'nightly',
        ]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          rustup install ${{ matrix.rust-version }}
          rustup default ${{ matrix.rust-version }}
      - name: Run integration tests
        run: |
          ./test.sh
